go_arch: amd64

alertmanager_user:   alertmanager
alertmanager_group:  alertmanager
alertmanager_uid:    2002

alertmanager_install_path:        /srv/alertmanager
alertmanager_config_path:         /srv/alertmanager/config
alertmanager_templates_path:      /srv/alertmanager/config/templates
alertmanager_data_path:           /srv/alertmanager/data

alertmanager_listen_address: "127.0.0.1:9093"

alertmanager_version: 0.6.1
alertmanager_download_url: https://github.com/prometheus/alertmanager/releases/download

alertmanager_slack_api_url: "{{ vault_alertmanager_slack_api_url }}"

alertmanager_tarball_url: "{{ alertmanager_download_url }}/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
alertmanager_path: "{{ alertmanager_install_path }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}"

alertmanager_smtp_from: "notifcations@ooni.io"
alertmanager_smtp_smarthost: "email-smtp.us-east-1.amazonaws.com:587"
alertmanager_smtp_username: "{{ vault_alertmanager_smtp_username }}"
alertmanager_smtp_password: "{{ vault_alertmanager_smtp_password }}"
