---
ipv4: 37.218.247.42

# for https://slack.openobservatory.org/
slackin_domains: slack.openobservatory.org -> http://slackin:3000
slackin_org: '{{ vault_slackin_org }}'
slackin_token: '{{ vault_slackin_token }}'

# for slack-irc gateway
slack_irc_dir: "/etc/slack-irc"
slack_irc_token: '{{ vault_slack_irc_token }}'
slacktopus_password: '{{ vault_slacktopus_password }}'

# IPv4 address is added to ACCESS list as there is some sort of race between
# services accepting IDENTIFY message and slack-irc trying to join. node-irc
# joins channel as soon as it sees MOTD and OFTC requires identification before
# joining for `+R` channels, see https://www.oftc.net/ChannelModes/
# Usage of IPv4 address in ACCESS LIST reduced race gap but does not eliminate
# it.  To add corresponding IPv4 address to the ACL do following while logging
# in as slacktopus.
#   /msg NickServ ACCESS ADD ~slacktopu@{{ ipv4 }}
# ircOptions.localAddress=ipv4 is not used as the process is running behind NAT
# in container.
#
# FIXME: used node-irc version does not respect `messageSplit` option and
# default value leads to messages that are split in the middle of word.
slack_irc_config: |
  [
    {
      "nickname": "slacktopus",
      "ircOptions": {
        "realName": "OONI Slack relay",
        "stripColors": true,
        "retryCount": 60,
        "retryDelay": 5000,
        "port": 6697,
        "secure": true,
        "autoSendCommands": [
          ["PRIVMSG", "NickServ", "GHOST slacktopus {{ slacktopus_password }}" ],
          ["NICK", "slacktopus"],
          ["PRIVMSG", "NickServ", "IDENTIFY {{ slacktopus_password }}"]
        ],
      },
      "server": "irc.oftc.net",
      "token": "{{ slack_irc_token }}",
      "channelMapping": {
        "#ooni": "#ooni",
        "#ooni-bots": "#ooni-bots",
        "#ooni-entropy": "#ooni-entropy"
      }
    }
  ]
