---
- name: Install nginx
  environment:
    RUNLEVEL: 1
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Remove default nginx virtual host
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  register: nginx

- name: Add nginx virtual host config
  template:
    src: proteus_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/proteus
    owner: root
    group: root
    mode: 0644
  register: nginx

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx.changed
