---
- name: Letsencrypt certificates renewal cronjob
  cron:
    name: "Renew ooni-backend letsencrypt certificates"
    user: "root"
    cron_file: letsencrypt_renew_certs
    month: "*/2"
    job: "{{ letsencrypt_renew_cmd }}"

