---
- name: install nginx if absent # should be installed as part of nginx-stable
  apt:
    name: nginx
    state: present
  environment:
    RUNLEVEL: 1 # To avoid nginx being launched right after it's installed


- name: create group
  group: name=ngxprom state=present

- name: create user
  user:
    name: "ngxprom"
    group: "ngxprom"
    comment: "nginx for Prometheus exporters"
    state: present

- name: Create nginx/Prometheus directories
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - '{{ ngxprom_base }}'
    - '{{ ngxprom_base }}/log'

- name: Upload Scraper CA
  copy: src=scraper_ca.cert dest={{ngxprom_ssl_dir}}/ owner=root group=root mode=0444

- name: cleanup stale files
  file: name={{item}} state=absent
  with_items:
    - /etc/nginx/sites-enabled/node_exporter
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/prometheus.htpasswd
    - /srv/node_exporter/private
    - /etc/init/nginx-prometheus.upstart
    - /etc/init.d/nginx-prometheus.rc
    - '{{ ngxprom_base }}/scraper.htpasswd'
  notify: reload nginx

- name: Create nginx conf file
  template:
    src: nginx.conf
    dest: "{{ ngxprom_base }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx-prometheus
  tags: on-renumber

- name: Create nginx systemd service file
  template: src=nginx-prometheus.service dest=/etc/systemd/system/ owner=root group=root mode=0444
  notify:
  - systemctl daemon-reload
  - restart nginx-prometheus
  when: ansible_service_mgr == 'systemd'

- name: Create nginx upstart service file
  template: src=nginx-prometheus.upstart dest=/etc/init/nginx-prometheus.conf owner=root group=root mode=0444
  notify: restart nginx-prometheus
  when: ansible_service_mgr == 'upstart'

- name: Create nginx sysvinit service file
  template: src=nginx-prometheus.rc dest=/etc/init.d/nginx-prometheus owner=root group=root mode=0555
  notify: restart nginx-prometheus
  when: ansible_service_mgr == 'sysvinit'

# `state: started` is postponed till `restart nginx-prometheus` handler
# otherwise daemon_reload is required for systemd, otherwise restart fails :)
- name: Enable and start nginx-prometheus service
  service:
    name: nginx-prometheus
    enabled: yes
