# different system may have different places for bash and nologin
- name: get shell path
  stat: path={{ item }} get_md5=no get_checksum=no
  register: shell_path
  with_items: [ /bin/bash, /usr/sbin/nologin ]

# combination of `assert` and `with_items` produces lots of visual noise
- name: check shell path
  assert: { that: 'shell_path.results | selectattr("stat.executable", "equalto", true) | list | length == shell_path.results | length' }

# You can also use something like:
# with_items: '{{ ["user", "fooser", "luser", "us3r"] | map("extract", passwd) | list }}'

- name: create group
  group: name={{ item.login }} state=present
  with_items: '{{ passwd.values() }}'
  loop_control:
    label: '{{ item.login }}'

- name: create user
  user:
    name: '{{ item.login }}'
    group: '{{ item.login }}'
    comment: '{{ item.comment }}'
    shell: '{{ (item.id >= 10000) | ternary("/bin/bash", "/usr/sbin/nologin") }}'
    createhome: '{{ item.id >= 10000 }}'
    home: '{{ (item.id >= 10000) | ternary("/home/" ~ item.login, "/nonexistent") }}'
    state: present
  with_items: "{{ passwd.values() }}"
  loop_control:
    label: "{{ item.login }}"

