# s3_ooni_open_data_access_key: "{{ vault_s3_ooni_open_data_access_key }}"
jwt_encryption_key: "{{ vault_jwt_encryption_key }}"
github_token: "{{ vault_github_token }}"
mail_smtp_password: "{{ vault_mail_smtp_password }}"
tor_targets: "{{ vault_tor_targets }}"
psiphon_config: "{{ vault_orchestra_psiphon_config_file_content }}"
# digital_ocean_token: "{{ vault_digital_ocean_token }}"
