- name: create group
  group: name=orchfrontend state=present

- name: create user
  user:
    name: "orchfrontend"
    group: "orchfrontend"
    comment: "orchfrontend for Orchestra"
    state: present

- name: get the user ids
  shell: >
    egrep "^orchfrontend:" /etc/passwd | awk -F: '{ print $3":"$4 }'
  changed_when: false
  register: user_group_id

- name: set permissions, owner and group
  file:
    path: "/srv/orchestra-frontend"
    state: directory
    owner: "orchfrontend"
    group: "orchfrontend"
    mode: "go-w"
    recurse: yes

- name: docker run orchestra-frontend
  docker_container:
    image: openobservatory/orchestra-frontend:20191022-03bdf4c4
    name: orchestra-frontend
    hostname: orchestra-frontend
    network_mode: 'host'
    purge_networks: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    env:
      NODE_ENV: "{{ orchestra_environment }}"
      PORT: "{{ orchestra_frontend_port | string }}"
      REGISTRY_URL: "{{ orchestra_registry_url }}"
      ORCHESTRATE_URL: "{{ orchestra_orchestrate_url }}"
    # XXX
    # Cannot run as the user due to permissions issues with the docker build.
    # The problem lies in the fact that we need to rebuild it to inject the environment variables.
    # A better solution should be devised. See: https://github.com/ooni/orchestra/issues/70
    # user: "{{ user_group_id.stdout }}"
    stop_timeout: 60 # default is 10
    restart_policy: unless-stopped

- name: Add nginx virtual host config
  template:
    src: orchestra-nginx
    dest: /etc/nginx/sites-enabled/orchestra
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: delete letsencrypt nginx config
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/letsencrypt-http"
  notify: restart nginx
