---

- name: Install smartmon package
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - smartmontools

- name: Install smartmon metrics tool
  copy:
    src: smartmon_metrics.sh
    dest: /usr/local/sbin/smartmon_metrics.sh
    owner: root
    mode: 0755

- name: Install smartmon_metrics systemd service file
  notify:
  - reload systemd
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - smartmon_metrics.service
    - smartmon_metrics.timer

- name: Enable smartmon_metrics service
  service:
    name: "{{ item }}"
    enabled: True
  with_items:
    - smartmon_metrics.service

- name: Enable and start smartmon_metrics timer
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - smartmon_metrics.timer
