---

- name: runs oonibackend bundle docker image
  docker_container:
    state: started
    name: "{{ docker_img_name }}"
    image: "{{ docker_img_name }}"
    expose:
    - "{{ tls_bouncer_port }}"
    - "{{ tcp_bouncer_port }}"
    - "{{ tls_collector_port }}"
    - "{{ tcp_collector_port }}"
    - "{{ tls_web_connectivity_port }}"
    - "{{ tcp_web_connectivity_port }}"
    ports:
    - "{{ docker_ip }}:{{ tls_bouncer_port }}:{{ tls_bouncer_port }}"
    - "{{ docker_ip }}:{{ tcp_bouncer_port }}:{{ tcp_bouncer_port }}"
    - "{{ docker_ip }}:{{ tls_collector_port }}:{{ tls_collector_port }}"
    - "{{ docker_ip }}:{{ tcp_collector_port }}:{{ tcp_collector_port }}"
    - "{{ docker_ip }}:{{ tls_web_connectivity_port }}:{{ tls_web_connectivity_port }}"
    - "{{ docker_ip }}:{{ tcp_web_connectivity_port }}:{{ tcp_web_connectivity_port }}"
    volumes:
    - "{{ bind_deck_dir }}:{{ deck_dir }}"
    - "{{ bind_input_dir }}:{{ input_dir }}"
    - "{{ bind_oonibackend_log_path }}:{{ oonibackend_log_path }}"
    - "{{ bind_oonibackend_conf_path }}:{{ oonibackend_conf_path }}"
    - "{{ bind_oonibackend_data_path }}:{{ oonibackend_data_path }}"
    restart_policy: always
  when: ( oonibackend_bundle is defined and oonibackend_bundle == True )

- name: runs oonibackend bouncer docker image
  docker_container:
    state: started
    name: "{{ docker_img_name }}"
    image: "{{ docker_img_name }}"
    expose:
    - "{{ tls_bouncer_port }}"
    - "{{ tcp_bouncer_port }}"
    ports:
    - "{{ docker_ip }}:{{ tls_bouncer_port }}:{{ tls_bouncer_port }}"
    - "{{ docker_ip }}:{{ tcp_bouncer_port }}:{{ tcp_bouncer_port }}"
    volumes:
    - "{{ bind_deck_dir }}:{{ deck_dir }}"
    - "{{ bind_input_dir }}:{{ input_dir }}"
    - "{{ bind_oonibackend_log_path }}:{{ oonibackend_log_path }}"
    - "{{ bind_oonibackend_conf_path }}:{{ oonibackend_conf_path }}"
    - "{{ bind_oonibackend_data_path }}:{{ oonibackend_data_path }}"
    restart_policy: always
  when: enable_bouncer is defined

- name: runs ooni-backend collector docker image
  docker_container:
    state: started
    name: "{{ docker_img_name }}"
    image: "{{ docker_img_name }}"
    expose:
    - "{{ tls_collector_port }}"
    - "{{ tcp_collector_port }}"
    ports:
    - "{{ docker_ip }}:{{ tls_collector_port }}:{{ tls_collector_port }}"
    - "{{ docker_ip }}:{{ tcp_collector_port }}:{{ tcp_collector_port }}"
    volumes:
    - "{{ bind_deck_dir }}:{{ deck_dir }}"
    - "{{ bind_input_dir }}:{{ input_dir }}"
    - "{{ bind_oonibackend_log_path }}:{{ oonibackend_log_path }}"
    - "{{ bind_oonibackend_conf_path }}:{{ oonibackend_conf_path }}"
    - "{{ bind_oonibackend_data_path }}:{{ oonibackend_data_path }}"
    restart_policy: always
  when: (enable_tcp_collector is defined) or (enable_tls_alternate is defined)

- name: runs oonibackend web_connectivity test helper docker image
  docker_container:
    state: started
    name: "{{ docker_img_name }}"
    image: "{{ docker_img_name }}"
    expose:
    - "{{ tls_web_connectivity_port }}"
    - "{{ tcp_web_connectivity_port }}"
    ports:
    - "{{ docker_ip }}:{{ tls_web_connectivity_port }}:{{ tls_web_connectivity_port }}"
    - "{{ docker_ip }}:{{ tcp_web_connectivity_port }}:{{ tcp_web_connectivity_port }}"
    volumes:
    - "{{ bind_deck_dir }}:{{ deck_dir }}"
    - "{{ bind_input_dir }}:{{ input_dir }}"
    - "{{ bind_oonibackend_log_path }}:{{ oonibackend_log_path }}"
    - "{{ bind_oonibackend_conf_path }}:{{ oonibackend_conf_path }}"
    - "{{ bind_oonibackend_data_path }}:{{ oonibackend_data_path }}"
    restart_policy: always
  when: enable_web_connectivity is defined
