- name: create group
  group: name=oonirun state=present

- name: create user
  user:
    name: "oonirun"
    group: "oonirun"
    comment: "OONI Run webservice"
    state: present

- name: get the user ids
  shell: >
    egrep "^oonirun:" /etc/passwd | awk -F: '{ print $3":"$4 }'
  changed_when: false
  register: user_group_id

- name: mkdir for oonirun home
  file:
    path: "{{ item }}"
    state: directory
    owner: "oonirun"
    group: "oonirun"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "/srv/oonirun"
    - "/srv/oonirun/home"

- name: docker run ooni-run
  docker_container:
    image: openobservatory/run:20191029-45266451
    name: ooni-run
    hostname: ooni-run
    network_mode: 'host'
    purge_networks: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /srv/oonirun/home:/home/oonirun:rw
    user: "{{ user_group_id.stdout }}"
    stop_timeout: 60 # default is 10
    restart_policy: unless-stopped

- name: Add nginx virtual host config
  template:
    src: ooni-run-nginx
    dest: /etc/nginx/sites-enabled/ooni-run
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: delete letsencrypt nginx config
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/letsencrypt-http"
  notify: restart nginx
