---
adm_logins: [ weasel, art, darkk, sbs, superq ]

# That's the password that other nodes do NOT store in config files,
# other nodes store SSHA() of it that is in group_vars/all
prometheus_scraper_password: '{{ vault_prometheus_scraper_password }}'

prometheus_basic_auth_password: "{{ vault_prometheus_basic_auth_password }}"
alertmanager_slack_api_url: '{{ vault_alertmanager_slack_api_url }}'
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_secret_key: "{{ vault_grafana_secret_key }}" # to sign cookies

ngxprom_exporter_ports:
  9100: '{{ node_exporter_ipv4 }}'
  8090: '127.0.0.1' # FIXME: unusual port for prometheus
  9093: '127.0.0.1'

blackbox_jobs:
  - name: "ooni web_connectivity test helpers"
    module: "ooni_web_connectivity_ok"
    targets:
      #- "https://a.web-connectivity.th.ooni.io/status"
      - "https://b.web-connectivity.th.ooni.io/status"
      - "https://c.web-connectivity.th.ooni.io/status"
  - name: "ooni collector"
    module: "ooni_collector_ok"
    targets:
      #- "https://a.collector.ooni.io/invalidpath"
      - "https://b.collector.ooni.io/invalidpath"
      - "https://c.collector.ooni.io/invalidpath"
      # Testing collectors
      - "https://b.collector.test.ooni.io/invalidpath"
  - name: "ooni bouncer"
    module: "ooni_bouncer_ok"
    targets:
      - "https://bouncer.ooni.io/bouncer"

  - name: "ooni tcp echo"
    module: "ooni_tcp_echo_ok"
    targets:
      - "37.218.247.110:80"
      - "213.138.109.232:80"

  - name: "ooni http return json headers"
    module: "ooni_http_return_json_headers_ok"
    targets:
      - "http://37.218.247.95:80"

  - name: "ooni explorer countByCountry"
    module: "http_2xx"
    targets:
      - "https://explorer.ooni.torproject.org/api/reports/countByCountry"

  - name: "ooni measurements API files"
    module: "http_2xx"
    targets:
      - "https://measurements.ooni.torproject.org/api/v1/files"

  - name: "slack inviter"
    module: "http_2xx"
    targets:
      - "https://slack.openobservatory.org"

  - name: "ooni website"
    module: "http_2xx"
    targets:
      - "https://ooni.torproject.org"

  - name: "ooni get"
    module: "http_2xx"
    targets:
      - "https://get.ooni.torproject.org"

  - name: "orchestrate"
    module: "ooni_orchestrate"
    targets: [ "orchestrate.ooni.io:443" ]

  - name: "registry"
    module: "ooni_registry"
    targets: [ "registry.proteus.ooni.io:443" ]

  - name: "proteus"
    module: "ooni_proteus"
    targets: [ "proteus.ooni.io:443" ]

  - name: "tor testhelper" # see also SSLCertExpires in roles/prometheus/files/alert_rules.yml
    module: tls_snakeoil
    targets: "{{ groups['have_tor'] | map('regex_replace', '$', ':9001') | list }}"
...
