go_arch: amd64

prometheus_user:   prometheus
prometheus_group:  prometheus

prometheus_install_path:         /srv/prometheus
prometheus_config_path:          /srv/prometheus/config
prometheus_db_path:              /srv/prometheus/data
prometheus_rule_path:            "{{ prometheus_config_path }}/rules"
prometheus_file_sd_config_path:  "{{ prometheus_config_path }}/targets"

prometheus_listen_address: ":9090"

prometheus_version: 1.5.2
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download

prometheus_tarball_url: "{{ prometheus_download_url }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
prometheus_path: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}"

