# well, it's not "pipeline" at the moment :-)
ooni_pipeline_host: '{{ CHANGE_ME }}'
ooni_pipeline_db: ooni_pipeline
ooni_pipeline_user: ooni
ooni_pipeline_passwd: '{{ CHANGE_ME }}'
# for upgrade
explorer_tag: '20180221-16a4b071'
explorer_backend_ipv4: 172.28.14.254
explorer_backend_port: 3000 # hardcoded in the image
