s3_ooni_open_data_access_key: "{{ vault_s3_ooni_open_data_access_key }}"
amspg_ooni_org_onion_key: "{{ vault_amspg_ooni_org_onion_key }}"
jwt_encryption_key: "{{ vault_jwt_encryption_key }}"
account_id_hashing_key: "{{ vault_account_id_hashing_key }}"
github_token: "{{ vault_github_token }}"
mail_smtp_password: "{{ vault_mail_smtp_password }}"
base_url: "https://ams-pg.ooni.org/"
tor_targets: "{{ vault_tor_targets }}"
psiphon_config: "{{ vault_orchestra_psiphon_config_file_content }}"
digital_ocean_token: "{{ vault_digital_ocean_token }}"
ooni_datadog_checks:
  journald:
    logs:
    - type: journald
      container_mode: true
  openmetrics:
    instances:
      - openmetrics_endpoint: "http://localhost:9090/metrics"
        namespace: "ooniprom"
        metrics:
          - "^prom.+"
          - "^net_.+"
          - "^go_.+"
  statsd:
    instances:
      - host: localhost
        port: 8126
        service: "oonimonitoring"
