---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Add NodeSource apt package signing key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

- name: Add NodeSource apt repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main'

- name: Install required nodejs via apt
  apt:
    name: nodejs

- include: install-yarn.yml
  when: install_yarn | bool == true
