---
ipv4: 37.218.240.67
ipv4gw: 37.218.240.254
ipv4mask: 24

docker_apt_ver: "=1.12.6-0~debian-jessie" # should be in sync with openobservatory/airflow-worker image

# bunch of containers is deployed only at this host
airflow_fernet_key: "{{ vault_airflow_fernet_key }}"
airflow_redis_password: "{{ vault_airflow_redis_password }}"
airflow_postgres_password: "{{ vault_airflow_postgres_password }}"
shovel_postgres_password: "{{ vault_shovel_postgres_password }}"
