---
# That's hotfix for https://github.com/ooni/sysadmin/issues/287
- name: remove broken jessie repos
  apt_repository:
    repo: '{{ item }}'
    state: absent
  with_items:
    - 'deb http://httpredir.debian.org/debian jessie-backports main'
    - 'deb http://ftp.nl.debian.org/debian jessie-updates main non-free contrib'

- name: install some common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 28800
    install_recommends: false
  with_items:
    - ca-certificates
    - tmux
    - screen # art@ prefers :) old-school
    - vim
    - lsof
    - strace
    - tcpdump
    - curl
    - mtr
    - rsync
    - openssl # at least for ooca-cert

- import_tasks: sshd.yml
  tags: sshd
- import_tasks: ping.yml
  tags: ping
...
