---
# That's hotfix for https://github.com/ooni/sysadmin/issues/287
- name: remove broken jessie repos
  tags: [remove-jessie]
  apt_repository:
    repo: '{{ item }}'
    state: absent
  with_items:
    - 'deb http://httpredir.debian.org/debian jessie-backports main'
    - 'deb http://ftp.nl.debian.org/debian jessie-updates main non-free contrib'
    - 'deb http://ftp.us.debian.org/debian jessie-updates main non-free contrib'
    - 'deb http://ftp.debian.org/debian jessie-backports main'

- name: install some common packages
  apt:
    name:
      - bash-completion
      - ca-certificates
      - curl
      - file
      - iotop
      - lsof
      - man-db
      - mtr
      - openssl
      - rsync
      - screen
      - strace
      - tcpdump
      - tmux
      - vim
    state: latest
    update_cache: yes
    cache_valid_time: 28800
    install_recommends: false
- import_tasks: sshd.yml
  tags: sshd
- import_tasks: ping.yml
  tags: ping
...
