- name: Install config file
  template:
    src: blackbox.yml.j2
    dest: "/etc/prometheus/blackbox.yml"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart blackbox_exporter
  tags: blackbox_exporter

- name: Setcap
  command: setcap cap_net_raw=ep /usr/bin/prometheus-blackbox-exporter
  tags: blackbox_exporter
  notify:
    - restart blackbox_exporter
