---
ansible_become: false # keep current UID at localhost as all other hosts use `sudo` in group_vars/all
gh_token: '{{ vault_gh_token }}'
namecheap_user: '{{ vault_namecheap_user }}'
namecheap_token: '{{ vault_namecheap_token }}'
namecheap_jumphosts: '{{ vault_namecheap_jumphosts }}'
