go_arch: amd64

orchestra_user:   prtnotif
orchestra_group:  prtnotif

orchestra_install_path: /srv/proteus
orchestra_data_path: /srv/proteus/data
orchestra_config_path: /srv/proteus/config

orchestra_environment: "production"
orchestra_log_level: "info"
orchestra_api_port: 9081
orchestra_api_address: "127.0.0.1"
orchestra_notify_https_port: 8081
orchestra_database_url: "postgres://proteus:{{ orchestra_database_password }}@{{ orchestra_db_hostname }}:5432/proteus?sslmode=require"
orchestra_auth_jwt_secret : "{{ orchestra_auth_jwt_secret }}"

orchestra_fcm_server_key: "{{ fcm_server_key }}"
orchestra_apn_key_path: "{{ orchestra_config_path }}/apn-key.pem"
orchestra_apn_key_password: "{{ orchestra_apn_key_password }}"
orchestra_apn_production: "{{ orchestra_environment == 'production' }}"
orchestra_apn_key_content: "{{ orchestra_apn_key_content }}"

orchestra_version: "0.1.0-beta.9"
orchestra_download_url: https://github.com/ooni/orchestra/releases/download

orchestra_tarball_url: "{{ orchestra_download_url }}/v{{ orchestra_version }}/orchestra-notify-{{ orchestra_version }}.linux-{{ go_arch }}.tar.gz"
orchestra_path: "{{ orchestra_install_path }}/orchestra-notify-{{ orchestra_version }}.linux-{{ go_arch }}"

gorush_version: "1.9.0"
gorush_download_url: "https://github.com/appleboy/gorush/releases/download"
gorush_url: "{{ gorush_download_url }}/v{{ gorush_version }}/gorush-v{{ gorush_version }}-linux-{{ go_arch }}"
gorush_path: "{{ orchestra_install_path }}/gorush-v{{ gorush_version }}-linux-{{ go_arch }}"

notification_backend: "gorush"
orchestra_notify_basic_auth_user: "orchestra"
orchestra_notify_basic_auth_password: "{{ orchestra_notify_basic_auth_password }}"
