---
- import_playbook: ansible-version.yml

- hosts: "ams-wcth3.ooni.nu"
  roles:
    - role: letsencrypt
      letsencrypt_domains:
        - "ams-wcth3.ooni.nu"
        - "wcth.ooni.io"
        - "a.web-connectivity.th.ooni.io"
        - "b.web-connectivity.th.ooni.io"
        - "c.web-connectivity.th.ooni.io"
    - role: th-web-connectivity
      tags: wcth
      with_pip: yes
      web_connectivity_domain: ams-wcth3.ooni.nu
    - role: onion-service
      tags: tor
      onion_services:
        - "{{ wcth_onion_service }}"


- hosts: "ams-wcth2.ooni.nu"
  roles:
    - role: letsencrypt
      letsencrypt_domains:
        - "ams-wcth2.ooni.nu"
    - role: th-web-connectivity
      tags: wcth
      with_pip: yes
      web_connectivity_domain: ams-wcth2.ooni.nu
    - role: onion-service
      tags: tor
      onion_services:
        - "{{ wcth_onion_service }}"

- hosts: "mia-wcth.ooni.io"
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "mia-wcth.ooni.io"
    - role: th-web-connectivity
      tags: wcth
      web_connectivity_domain: mia-wcth.ooni.io

- hosts: "ams-wcth.ooni.nu"
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - "ams-wcth.ooni.nu"
    - role: th-web-connectivity
      tags: wcth
      web_connectivity_domain: ams-wcth.ooni.nu
