---
- import_playbook: ansible-version.yml

- hosts: hkgcollectora.ooni.nu
  # TODO: `have_collector` instead of `hkgcollectora.ooni.nu`
  roles:
    - role: docker_py
    - role: letsencrypt
      letsencrypt_nginx: true
      letsencrypt_domains: a.collector.ooni.io

- hosts: hkgcollectora.ooni.nu
  gather_facts: false
  vars:
    ansible_python_interpreter: '/root/venv/bin/python2.7'
  roles:
    - role: ooni-collector
      collector_domain: a.collector.ooni.io
