---
- import_playbook: ansible-version.yml

- hosts: amsapi.ooni.nu
  roles:
    - role: docker_py
    - role: letsencrypt
      letsencrypt_nginx: true
      letsencrypt_domains: ["api.ooni.io"]
    - role: letsencrypt
      letsencrypt_nginx: true
      letsencrypt_domains: ["measurements.ooni.io", "measurements.ooni.torproject.org"]
      tags: legacy

- hosts: hkgmetadb.infra.ooni.io
  gather_facts: false # no useful facts there :)
  roles:
    - role: pguser-readonly
      login_user: shovel # FIXME: revoke superuser access from this user :)
      login_password: '{{ shovel_postgres_password }}'
      db: metadb
      name: oomsm-beta
      password: '{{ oomsm_beta_postgres_password }}'

    - role: pguser-readonly
      login_user: shovel # FIXME: revoke superuser access from this user :)
      login_password: '{{ shovel_postgres_password }}'
      db: metadb
      name: amsapi
      password: '{{ metadb_amsapi_password }}'

- hosts: amsapi.ooni.nu
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: '/root/venv/bin/python2.7'
  roles:
    - role: ooni-measurements
      tags: measurements
      oomsm_domain: api.ooni.io
