---
- hosts: local:staging:testing
  vars:
    enable_tls_bouncer: yes
    enable_tls_collector: yes
    enable_tls_web_connectivity: yes
    enable_bouncer: yes
  roles:
  - common
  - { role: supervisord, when "set_supervisord == 'true'" }
  - ooni-backend
