---
- name: create group
  group:
    name: explorer
    state: present

- name: create user
  user:
    name: "explorer"
    comment: "User to run docker container"
    state: present
  register: user

- name: create group
  group:
    name: explorer
    state: present
  register: group

- name: ams-explorer nginx config
  template: src=ngx-explorer dest=/etc/nginx/sites-enabled/explorer
  tags: nginx
  notify: reload nginx

- name: docker network for explorer
  docker_network:
    name: explrr
    driver_options:
      com.docker.network.bridge.name: brexplrr
    ipam_config:
      - subnet: 172.27.33.0/24
        gateway: 172.27.33.1

- name: OONI Explorer webservice
  docker_container:
    image: openobservatory/explorer-next:{{ explorer_next_tag }}
    name: explorer
    hostname: explorer
    network_mode: 'host'
    purge_networks: true
    env:
      NODE_ENV: production
      CLOUDFLARE_API_EMAIL: "{{ cloudflare_api_email }}"
      CLOUDFLARE_API_TOKEN_SECRET: "{{ cloudflare_api_token_secret }}"
    user: "{{ user.uid }}:{{ group.gid }}"
    restart_policy: unless-stopped

...
