oonibackend_package: oonibackend
enable_dns_helper: yes
enable_dns_discovery_helper: yes
enable_http_return_json_headers_helper: yes
enable_tcp_echo_helper: yes
enable_ssl_helper: no
enable_daphn3_helper: yes

dns_resolver_address: "8.8.8.8:53"

http_return_json_headers_port: 57001
tcp_echo_port: 57002
daphn3_port: 57003
dns_port_tcp: 57004
dns_port_udp: 57004
dns_discover_port_tcp: 57005
dns_discover_port_udp: 57005
ssl_port: 57006

enable_bouncer: no
enable_policy: no
oonibackend_data_path: /usr/share/ooni/backend
archive_dir: "{{ oonibackend_data_path }}/archive"
tor_datadir: "{{ oonibackend_data_path }}/tor"
bouncer_file: "{{ oonibackend_data_path }}/bouncer.yaml"
policy_file: "{{ oonibackend_data_path }}/policy.yaml"
deck_dir: "{{ oonibackend_data_path }}/decks"
input_dir: "{{ oonibackend_data_path }}/inputs"
report_dir: "{{ oonibackend_data_path }}/raw_reports"

oonibackend_install_path: /opt/ooni-backend
oonibackend_log_path: /var/log/ooni
oonibackend_conf: /etc/oonibackend.conf
oonibackend_log_file_name: oonibackend.log
